import csv

stations_red_line = [
    ("Shaheed Sthal (New Bus Adda)", "red_line", 1),
    ("Hindon", "red_line", 2),
    ("Arthala", "red_line", 3),
    ("Mohan Nagar", "red_line", 4),
    ("Shyam Park", "red_line", 5),
    ("Major Mohit Sharma (Rajendra Nagar)", "red_line", 6),
    ("Raj Bagh", "red_line", 7),
    ("Shaheed Nagar", "red_line", 8),
    ("Dilshad Garden", "red_line", 9),
    ("Jhilmil", "red_line", 10),
    ("Mansarovar Park", "red_line", 11),
    ("Shahdara", "red_line", 12),
    ("Welcome", "red_line", 13),
    ("Seelampur", "red_line", 14),
    ("Shastri Park", "red_line", 15),
    ("Kashmere Gate", "red_line", 16),
    ("Tis Hazari", "red_line", 17),
    ("Pul Bangash", "red_line", 18),
    ("Pratap Nagar", "red_line", 19),
    ("Shastri Nagar", "red_line", 20),
    ("Inderlok", "red_line", 21),
    ("Kanhaiya Nagar", "red_line", 22),
    ("Keshav Puram", "red_line", 23),
    ("Netaji Subhash Place", "red_line", 24),
    ("Kohat Enclave", "red_line", 25),
    ("Pitampura", "red_line", 26),
    ("Rohini East", "red_line", 27),
    ("Rohini West", "red_line", 28),
    ("Rithala", "red_line", 29),
]
stations_yellow_line = [
    ("Samaypur Badli", "yellow_line", 1),
    ("Rohini Sector 18, 19", "yellow_line", 2),
    ("Haiderpur Badli Mor", "yellow_line", 3),
    ("Jahangirpuri", "yellow_line", 4),
    ("Adarsh Nagar", "yellow_line", 5),
    ("Azadpur", "yellow_line", 6),
    ("Model Town", "yellow_line", 7),
    ("GTB Nagar", "yellow_line", 8),
    ("Vishwavidyalaya", "yellow_line", 9),
    ("Vidhan Sabha", "yellow_line", 10),
    ("Civil Lines", "yellow_line", 11),
    ("Kashmere Gate", "yellow_line", 12),
    ("Chandni Chowk", "yellow_line", 13),
    ("Chawri Bazar", "yellow_line", 14),
    ("New Delhi", "yellow_line", 15),
    ("Rajiv Chowk", "yellow_line", 16),
    ("Patel Chowk", "yellow_line", 17),
    ("Central Secretariat", "yellow_line", 18),
    ("Udyog Bhawan", "yellow_line", 19),
    ("Lok Kalyan Marg", "yellow_line", 20),
    ("Jor Bagh", "yellow_line", 21),
    ("Dilli Haat - INA", "yellow_line", 22),
    ("AIIMS", "yellow_line", 23),
    ("Green Park", "yellow_line", 24),
    ("Hauz Khas", "yellow_line", 25),
    ("Malviya Nagar", "yellow_line", 26),
    ("Saket", "yellow_line", 27),
    ("Qutab Minar", "yellow_line", 28),
    ("Chhatarpur", "yellow_line", 29),
    ("Sultanpur", "yellow_line", 30),
    ("Ghitorni", "yellow_line", 31),
    ("Arjan Garh", "yellow_line", 32),
    ("Guru Dronacharya", "yellow_line", 33),
    ("Sikandarpur", "yellow_line", 34),
    ("MG Road", "yellow_line", 35),
    ("IFFCO Chowk", "yellow_line", 36),
    ("Millennium City Centre Gurugram", "yellow_line", 37),
]
stations_blue_line_main = [
    ("Noida Electronic City", "blue_line_main", 1),
    ("Noida Sector 62", "blue_line_main", 2),
    ("Noida Sector 59", "blue_line_main", 3),
    ("Noida Sector 61", "blue_line_main", 4),
    ("Noida Sector 52", "blue_line_main", 5),
    ("Noida Sector 34", "blue_line_main", 6),
    ("Noida City Centre", "blue_line_main", 7),
    ("Golf Course", "blue_line_main", 8),
    ("Botanical Garden", "blue_line_main", 9),
    ("Noida Sector 18", "blue_line_main", 10),
    ("Noida Sector 16", "blue_line_main", 11),
    ("Noida Sector 15", "blue_line_main", 12),
    ("New Ashok Nagar", "blue_line_main", 13),
    ("Mayur Vihar Extension", "blue_line_main", 14),
    ("Mayur Vihar–I", "blue_line_main", 15),
    ("Akshardham", "blue_line_main", 16),
    ("Yamuna Bank", "blue_line_main", 17),  # Branch point to Vaishali
    ("Indraprastha", "blue_line_main", 18),
    ("Supreme Court", "blue_line_main", 19),
    ("Mandi House", "blue_line_main", 20),
    ("Barakhamba Road", "blue_line_main", 21),
    ("Rajiv Chowk", "blue_line_main", 22),
    ("Ramakrishna Ashram Marg", "blue_line_main", 23),
    ("Jhandewalan", "blue_line_main", 24),
    ("Karol Bagh", "blue_line_main", 25),
    ("Rajendra Place", "blue_line_main", 26),
    ("Patel Nagar", "blue_line_main", 27),
    ("Shadipur", "blue_line_main", 28),
    ("Kirti Nagar", "blue_line_main", 29),
    ("Moti Nagar", "blue_line_main", 30),
    ("Ramesh Nagar", "blue_line_main", 31),
    ("Rajouri Garden", "blue_line_main", 32),
    ("Tagore Garden", "blue_line_main", 33),
    ("Subhash Nagar", "blue_line_main", 34),
    ("Tilak Nagar", "blue_line_main", 35),
    ("Janakpuri East", "blue_line_main", 36),
    ("Janakpuri West", "blue_line_main", 37),
    ("Uttam Nagar East", "blue_line_main", 38),
    ("Uttam Nagar West", "blue_line_main", 39),
    ("Nawada", "blue_line_main", 40),
    ("Dwarka Mor", "blue_line_main", 41),
    ("Dwarka", "blue_line_main", 42),
    ("Dwarka Sector 14", "blue_line_main", 43),
    ("Dwarka Sector 13", "blue_line_main", 44),
    ("Dwarka Sector 12", "blue_line_main", 45),
    ("Dwarka Sector 11", "blue_line_main", 46),
    ("Dwarka Sector 10", "blue_line_main", 47),
    ("Dwarka Sector 9", "blue_line_main", 48),
    ("Dwarka Sector 8", "blue_line_main", 49),
    ("Dwarka Sector 21", "blue_line_main", 50),
]
stations_blue_line_branch = [
    ("Yamuna Bank", "blue_line_branch", 1),
    ("Laxmi Nagar", "blue_line_branch", 2),
    ("Nirman Vihar", "blue_line_branch", 3),
    ("Preet Vihar", "blue_line_branch", 4),
    ("Karkarduma", "blue_line_branch", 5),
    ("Anand Vihar ISBT", "blue_line_branch", 6),
    ("Kaushambi", "blue_line_branch", 7),
    ("Vaishali", "blue_line_branch", 8),
]
stations_green_line_main = [
    ("Inderlok", "green_line_main", 1),
    ("Ashok Park Main", "green_line_main", 2), # Branch point to Kirti Nagar
    ("Punjabi Bagh", "green_line_main", 3),
    ("Shivaji Park", "green_line_main", 4),
    ("Moti Nagar", "green_line_main", 5),
    ("Kirti Nagar", "green_line_main", 6),
    ("Saraswati Vihar", "green_line_main", 7),
    ("Paschim Vihar East", "green_line_main", 8),
    ("Paschim Vihar West", "green_line_main", 9),
    ("Peeragarhi", "green_line_main", 10),
    ("Udyog Nagar", "green_line_main", 11),
    ("Surajmal Stadium", "green_line_main", 12),
    ("Nangloi", "green_line_main", 13),
    ("Nangloi Railway Station", "green_line_main", 14),
    ("Rajdhani Park", "green_line_main", 15),
    ("Mundka", "green_line_main", 16),
    ("Mundka Industrial Area (MIA)", "green_line_main", 17),
    ("Ghevra", "green_line_main", 18),
    ("Tikri Kalan", "green_line_main", 19),
    ("Tikri Border", "green_line_main", 20),
    ("Brigadier Hoshiyar Singh", "green_line_main", 21),
]

stations_green_line_branch = [
    ("Ashok Park Main", "green_line_branch", 1),
    ("Satguru Ram Singh Marg", "green_line_branch", 2),
    ("Kirti Nagar", "green_line_branch", 3),
]
stations_violet_line = [
    ("Kashmere Gate", "violet_line", 1),
    ("Lal Quila", "violet_line", 2),
    ("Jama Masjid", "violet_line", 3),
    ("Delhi Gate", "violet_line", 4),
    ("ITO", "violet_line", 5),
    ("Mandi House", "violet_line", 6),
    ("Janpath", "violet_line", 7),
    ("Central Secretariat", "violet_line", 8),
    ("Khan Market", "violet_line", 9),
    ("Jawaharlal Nehru Stadium", "violet_line", 10),
    ("Jangpura", "violet_line", 11),
    ("Lajpat Nagar", "violet_line", 12),
    ("Moolchand", "violet_line", 13),
    ("Kailash Colony", "violet_line", 14),
    ("Nehru Place", "violet_line", 15),
    ("Govind Puri", "violet_line", 16),
    ("Harkesh Nagar Okhla", "violet_line", 17),
    ("Jasola Vihar Shaheen Bagh", "violet_line", 18),
    ("Kalindi Kunj", "violet_line", 19),
    ("Okhla Bird Sanctuary", "violet_line", 20),
    ("Botanical Garden", "violet_line", 21),
    ("Noida Sector 44", "violet_line", 22),
    ("Noida Sector 45", "violet_line", 23),
    ("Noida Sector 46", "violet_line", 24),
    ("Noida Sector 47", "violet_line", 25),
    ("Noida Sector 48", "violet_line", 26),
    ("Noida Sector 49", "violet_line", 27),
    ("Noida Sector 50", "violet_line", 28),
    ("Noida Sector 51", "violet_line", 29),
    ("Noida Sector 52", "violet_line", 30),
    ("Noida Sector 53", "violet_line", 31),
    ("Noida Sector 54", "violet_line", 32),
    ("Noida Sector 55", "violet_line", 33),
    ("Noida Sector 56", "violet_line", 34),
    ("Noida Sector 57", "violet_line", 35),
    ("Noida Sector 58", "violet_line", 36),
    ("Noida Sector 59", "violet_line", 37),
    ("Noida Sector 60", "violet_line", 38),
    ("Noida Sector 61", "violet_line", 39),
    ("Noida Sector 62", "violet_line", 40),
    ("Noida Electronic City", "violet_line", 41),
]
stations_pink_line = [
    ("Majlis Park", "pink_line", 1),
    ("Azadpur", "pink_line", 2),
    ("Shalimar Bagh", "pink_line", 3),
    ("Netaji Subhash Place", "pink_line", 4),
    ("Shakurpur", "pink_line", 5),
    ("Punjabi Bagh West", "pink_line", 6),
    ("E.S.I. - Basaidarapur", "pink_line", 7),
    ("Rajouri Garden", "pink_line", 8),
    ("Mayapuri", "pink_line", 9),
    ("Naraina Vihar", "pink_line", 10),
    ("Delhi Cantt.", "pink_line", 11),
    ("Durgabai Deshmukh South Campus", "pink_line", 12),
    ("Sir Vishweshwaraiah Moti Bagh", "pink_line", 13),
    ("Bhikaji Cama Place", "pink_line", 14),
    ("Sarojini Nagar", "pink_line", 15),
    ("Dilli Haat - INA", "pink_line", 16),
    ("South Extension", "pink_line", 17),
    ("Lajpat Nagar", "pink_line", 18),
    ("Vinobapuri", "pink_line", 19),
    ("Ashram", "pink_line", 20),
    ("Hazrat Nizamuddin", "pink_line", 21),
    ("Mayur Vihar Phase-I", "pink_line", 22),
    ("Mayur Vihar Extension", "pink_line", 23),
    ("Tirath Singh Market", "pink_line", 24),
    ("Vinod Nagar East", "pink_line", 25),
    ("Vinod Nagar West", "pink_line", 26),
    ("IP Extension", "pink_line", 27),
    ("Mandawali - West Vinod Nagar", "pink_line", 28),
    ("Karkarduma", "pink_line", 29),
    ("Anand Vihar ISBT", "pink_line", 30),
    ("Jagatpuri", "pink_line", 31),
    ("Gokulpuri", "pink_line", 32),
    ("Maujpur - Babarpur", "pink_line", 33),
    ("Yamuna Vihar", "pink_line", 34),
    ("Jaffrabad", "pink_line", 35),
    ("Shakti Nagar", "pink_line", 36),
    ("Welcome", "pink_line", 37),
    ("Shiv Vihar", "pink_line", 38),
]
stations_airport_express_line = [
    ("New Delhi", "airport_express_line", 1),
    ("Shivaji Stadium", "airport_express_line", 2),
    ("Dhaula Kuan", "airport_express_line", 3),
    ("Delhi Aerocity", "airport_express_line", 4),
    ("IGI Airport (T-3)", "airport_express_line", 5),
    ("Dwarka Sector 21", "airport_express_line", 6),
    ("Yashobhoomi Dwarka Sector 25", "airport_express_line", 7), # Latest extension
]
stations_magenta_line = [
    ("Janakpuri West", "magenta_line", 1),
    ("Dabri Mor - Janakpuri South", "magenta_line", 2),
    ("Dashrath Puri", "magenta_line", 3),
    ("Palam", "magenta_line", 4),
    ("Sadar Bazaar Cantonment", "magenta_line", 5),
    ("Terminal 1-IGI Airport", "magenta_line", 6),
    ("Shankar Vihar", "magenta_line", 7),
    ("Vasant Vihar", "magenta_line", 8),
    ("Munirka", "magenta_line", 9),
    ("R K Puram", "magenta_line", 10),
    ("IIT Delhi", "magenta_line", 11),
    ("Hauz Khas", "magenta_line", 12),
    ("Panchsheel Park", "magenta_line", 13),
    ("Chirag Delhi", "magenta_line", 14),
    ("Greater Kailash", "magenta_line", 15),
    ("Nehru Enclave", "magenta_line", 16),
    ("Kalkaji Mandir", "magenta_line", 17),
    ("Okhla NSIC", "magenta_line", 18),
    ("Sukhdev Vihar", "magenta_line", 19),
    ("Jamia Millia Islamia", "magenta_line", 20),
    ("Okhla Vihar", "magenta_line", 21),
    ("Jasola Vihar Shaheen Bagh", "magenta_line", 22),
    ("Kalindi Kunj", "magenta_line", 23),
    ("Okhla Bird Sanctuary", "magenta_line", 24),
    ("Botanical Garden", "magenta_line", 25),
]
stations_grey_line = [
    ("Dwarka", "grey_line", 1),
    ("Nangli", "grey_line", 2),
    ("Najafgarh", "grey_line", 3),
    ("Dhansa Bus Stand", "grey_line", 4),
]

            
